CASM-3871 Grafana Upgrade and Dashboard improvements
Cray-HPE/container-images pull request #516
Opened 2023-02-13 10:39 UTC by sumithrb

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-02-13 11:39 UTC, rambabubolla approved these changes

2023-02-14 05:39 UTC, danielvaz46 requested changes
The piechart panel we are adding through the zip file is deprecated in Grafana 9.3.2. It is also no longer necessary as Grafana 8.x+ comes with the panel pre-installed. Please remove it, thanks.

2023-02-14 10:13 UTC, sumithrb commented
> The piechart panel we are adding through the zip file is deprecated in Grafana 9.3.2. It is also no longer necessary as Grafana 8.x+ comes with the panel pre-installed. Please remove it, thanks.

Removed the pie-chart zip lines. Check if the Vonage status panel still needs to be installed as done.

2023-02-15 05:47 UTC, danielvaz46 commented on docker.io/grafana/grafana/9.3.2/Dockerfile
> +RUN wget -nv https://grafana.com/api/plugins/vonage-status-panel/versions/latest/download -O /var/lib/grafana-plugins/vonage-status-panel-1.0.11.zip
Are we sure that we have permission to download from the panel from the internet directly?
The usual practice is that we either download it from our artifactory or we add a zip file to the repository which we can access using the COPY command within the Dockerfile.
Other than this, looks fine.

2023-02-15 05:47 UTC, danielvaz46 approved these changes

2023-02-15 06:24 UTC, sumithrb commented
> The piechart panel we are adding through the zip file is deprecated in Grafana 9.3.2. It is also no longer necessary as Grafana 8.x+ comes with the panel pre-installed. Please remove it, thanks.

@danielvaz46 I am getting the following error for piechart panels in dashboards while testing without using the old chart, I believe we still have to use the wget method for the plugin to work - 
![image](https://user-images.githubusercontent.com/110656037/218948958-9734f670-4aa0-4d6a-a709-a6fabc3181bc.png)

2023-02-15 06:26 UTC, sumithrb commented on docker.io/grafana/grafana/9.3.2/Dockerfile
> +RUN wget -nv https://grafana.com/api/plugins/vonage-status-panel/versions/latest/download -O /var/lib/grafana-plugins/vonage-status-panel-1.0.11.zip
Yes, these are open-source panels and hence, we can download them directly.

2023-02-16 13:47 UTC, rambabubolla approved these changes

2023-02-16 13:50 UTC, merged