CASMMON-418
Cray-HPE/container-images pull request #631
Opened 2024-08-20 04:40 UTC by rambabubolla

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-08-20 14:41 UTC, bo-quan requested changes

2024-08-20 14:41 UTC, bo-quan commented on .github/workflows/docker.io.victoriametrics.vminsert.v1.96.0-cluster.yaml
> +name: docker.io/victoriametrics/vminsert:v1.93.1-cluster
```suggestion
name: docker.io/victoriametrics/vminsert:v1.96.0-cluster
```

2024-08-20 14:51 UTC, itsvijaybs approved these changes

2024-08-21 05:29 UTC, rambabubolla commented on .github/workflows/docker.io.victoriametrics.vminsert.v1.96.0-cluster.yaml
> +name: docker.io/victoriametrics/vminsert:v1.93.1-cluster
Done

2024-08-21 05:32 UTC, itsvijaybs approved these changes

2024-08-21 05:34 UTC, shreni123 approved these changes

2024-08-21 14:45 UTC, bo-quan approved these changes

2024-08-21 14:45 UTC, merged